### ISSUE TITLE
Coinbase Wallet Error signing transactions: User canceled request

### ISSUE THREAD

**Issue by jasonchitla** [solana-labs/wallet-adapter#538] opened 2022-08-23 23:22 UTC
I am able to connect and sign transactions with all wallets except Im having an issue signing txs with Coinbase wallet. Anyone else?

I can connect to the coinbase wallet and view balance, but when i click the Confirm button in the Coinbase popup to approve tx, I get "Error signing transactions: User canceled request at CoinbaseWalletAdapter.signAllTransactions (adapter.ts:203:1)"

Using latest version of "@solana/wallet-adapter-wallets": "^0.18.4"

**Comment by jordansexton** [comment] 2022-08-23 23:57
Closing since this isn't the place for issues with specific wallets. If you have a reason to believe the issue is caused by the code in https://github.com/solana-labs/wallet-adapter/blob/master/packages/wallets/coinbase/src/adapter.ts, please expand on this and we can reopen it.

**Closed** 2022-08-23 23:56 UTC
Labels: question

**Comment by jordansexton** [comment] 2022-08-23 23:59
Tagging @brianchitester @biw for viz.

**Comment by scottwilson312** [comment] 2023-08-29 20:48
@jasonchitla did you ever solve this? I'm having the same issue a year later!

**Comment by aniket-solulab** [comment] 2024-07-26 12:16
Hey its b2024 still issue occurs on clicking the confirm button i get
 WalletSendTransactionError: User canceled request
    at CoinbaseWalletAdapter.sendTransaction
    
    error
