### ISSUE TITLE
When attempting to connect, if the user is coming through mobile web, deeplink to Phantom app's browser with the webpage URL

### ISSUE THREAD

**Issue by akelaholmes** [solana-labs/wallet-adapter#319] opened 2022-02-17 22:58 UTC
**Is your feature request related to a problem? Please describe.**
Since mobile web users will not be able to sign (no way for mobile Chrome or mobile Safari to have wallets), if the wallet they are trying to connect to has a mobile app, they should be deeplinked to that mobile wallet app's browser for the webpage to be properly interacted with / wallet connected. 

This is the same as how `coinbase-wallet-sdk` does. 

**Describe the solution you'd like**
^

**Describe alternatives you've considered**
Copy & paste URL into mobile wallet app's browser.

**Comment by jordansexton** [comment] 2022-02-20 18:25
Duplicate of #312, #311, #309. This is up to mobile wallets to implement first and cannot be added by wallet-adapter until the wallets support it.

**Closed by jordansexton** 2022-02-20 18:25 UTC

**Comment by Dubwoof** [comment] 2022-05-12 09:06
> 

Phantom Wallet added deep links. Do you plan to integrate it? I tried it - almost got through, but have issues with base58 encryption. I can share my code if you want.

**Comment by dreamchaser96** [comment] 2022-05-15 07:41
> 

Can you please share your code?

**Comment by Dubwoof** [comment] 2022-05-20 13:12
> > 
> 
> Can you please share your code?

Sure - hope you can help... The native app opens correctly. When returning to the website it shows an decryption error.
[https://codesandbox.io/s/phantom-wallet-provider-rd8l0j?file=/src/PhantomProvider.tsx](url)
