### ISSUE TITLE
issue while running disconnecting wallet

### ISSUE THREAD

**Issue by designOm** [solana-labs/wallet-adapter#185] opened 2021-12-01 10:12 UTC
**Here is Error string** 

index.js:48 WalletDisconnectedError
    at d.PhantomWalletAdapter._disconnected (adapter.ts:214)
    at d.i.emit (inpage.js:116)
    at d.<anonymous> (inpage.js:288)
    at Generator.next (<anonymous>)
    at inpage.js:288
    at new Promise (<anonymous>)
    at a (inpage.js:288)
    at d._handleDisconnect (inpage.js:288)
    at d.<anonymous> (inpage.js:288)
    at Generator.next (<anonymous>)
    at inpage.js:288
    at new Promise (<anonymous>)
    at a (inpage.js:288)
    at _handleMessage (inpage.js:288)

My code
	

```
<div            className="browseSubmenu__item tf-button2"
						onClick={handleWalletDisconnect}>
						<img width={20} src={Images.WalletDisconnectIcon} alt="I" />{" "}
						Disconnect
 					</div>
```

	const handleWalletDisconnect = () =>  {
		dispatch(disconnectWallet());
		disconnect().catch((e) => {
			// Silently catch because any errors are caught by the context `onError` handler
		});
		setAnchorEl(null)
	}

that disconnet  ia m taking from hook
const { wallet, disconnect } = useWallet();

**Comment by jordansexton** [comment] 2021-12-03 19:16
`WalletDisconnectedError` is typically thrown by the wallet adapter when the wallet itself is disconnected.

It looks like you want to disconnect the wallet manually, is that right? What does this do?

```
dispatch(disconnectWallet());
```

FWIW the example here showcases buttons in the UI packages of this library that can disconnect the wallet:

https://solana-labs.github.io/wallet-adapter/example/

**Comment by jordansexton** [comment] 2021-12-16 19:46
@designOm any more info on this? I don't have any steps to replicate.

**Comment by jordansexton** [comment] 2021-12-16 20:06
Closing this issue since the root cause is likely related to https://github.com/solana-labs/wallet-adapter/issues/186#issuecomment-996156439

**Closed by jordansexton** 2021-12-16 20:06 UTC
Labels: question, waiting

**Comment by davodesign84** [comment] 2023-03-08 10:29
Hi @jordansexton could we reopen this issue? Still seems to be an issue (well, more like an annoyance).

Here is a minimum reproducible case https://codesandbox.io/s/sad-williams-wuzl0m?file=/src/App.tsx but can also be observed on the wallet button demo page.

Some additional logging from one of my dev builds:
```
WalletDisconnectedError
    at eval (webpack-internal:///(app-client)/../node_modules/.pnpm/@solana+wallet-standard-wallet-adapter-base@1.0.1_@solana+web3.js@1.73.3/node_modules/@solana/wallet-standard-wallet-adapter-base/lib/esm/adapter.js:60:36)
    at inpage_sol.js:143:165382
    at Array.forEach (<anonymous>)
    at e.pt (inpage_sol.js:143:165352)
    at e.<anonymous> (inpage_sol.js:143:159111)
    at a.register.u.emit (inpage_sol.js:121:47717)
    at n.<anonymous> (inpage_sol.js:150:53647)
    at inpage_sol.js:10:210830
    at Object.next (inpage_sol.js:10:210935)
    at inpage_sol.js:150:50428
    at new Promise (<anonymous>)
    at ju (inpage_sol.js:150:50173)
    at i._handleDisconnect (inpage_sol.js:150:53494)
    at n.<anonymous> (inpage_sol.js:150:55217)
    at inpage_sol.js:10:210830
    at Object.next (inpage_sol.js:10:210935)
    at inpage_sol.js:150:50428
    at new Promise (<anonymous>)
    at ju (inpage_sol.js:150:50173)
    at i._handleMessage (inpage_sol.js:150:54274) StandardWalletAdapter {_events: Events, _eventsCount: 4}
    ```

I believe it comes from this line https://github.com/solana-labs/wallet-standard/blob/master/packages/wallet-adapter/base/src/adapter.ts#L203, by reading through this code and other wallets code, it would make sense for this error to be raised whenever there is an action (other than `disconnect`) but wallet is not currently connected and can not proceed. Happy to submit a PR to remove it.

**Comment by alchemist0803** [comment] 2023-03-30 18:36
> 

Hello, @jordansexton , I have just check this link for disconnecting wallet.
It's not working now.
I also have same problem on my site.
It never disconnected.
Please let me know the issues.
