### ISSUE TITLE
Wallet-adapter windows

### ISSUE THREAD

**Issue by odineH** [solana-labs/wallet-adapter#53] opened 2021-09-05 00:03 UTC
Hi, is there any way to run the wallet-adapter in windows? 

It's not working for me :(

**Comment by jordansexton** [comment] 2021-09-05 03:06
Are you building from source, and if so, have you followed the steps for building from source in the readme?

Please provide the steps you've taken, what error messages you're experiencing, and details about what exactly you're looking to do.

**Comment by odineH** [comment] 2021-09-05 11:16
Hi! 

Thanks for your quick reply!

I'm building from source following the readme instructions. 

I'm attaching two images showing the problems during the "build process" and yarn install


![image](https://user-images.githubusercontent.com/79032843/132124773-6f6b6c06-2543-40a4-b66c-c7837e272bf1.png)
![image (2)](https://user-images.githubusercontent.com/79032843/132124780-42427416-324b-4b27-8ab9-c0e95a588700.png)

kind regards,

odineH

**Comment by jordansexton** [comment] 2021-09-05 14:00
Ahh I see the problem. The issue is that the `yarn clean` command is running `rm` to clear the build directory, be which is missing on windows. I can replace this with a cross platform utility.

A workaround would be to install bash on Windows: https://docs.microsoft.com/en-us/windows/wsl/install-win10

I'll get this changed quickly though.

**Comment by jordansexton** [comment] 2021-09-05 15:19
Fixed with 6d336873b3f6d397b94124f52aa96f352cd33a56

**Closed by jordansexton** 2021-09-05 15:19 UTC
