### ISSUE TITLE
Dropdown close (not open on connect)

### ISSUE THREAD

**Issue by MarioProjects** [solana-labs/wallet-adapter#349] opened 2022-03-08 18:41 UTC
Hello!

First of all thanks for your amazing work. I am integrating the wallet adapter and facing some strange, at least for me, behavior. When the user connects the wallet, the dropdown opens instantaneously before. There is an option to close it or even better not open it? Screenshot: https://ibb.co/Xtgb9Q2

Thanks again!

**Comment by jordansexton** [comment] 2022-03-08 18:56
Hmm, I'm not sure I understand what's happening. Can you describe the exact actions taken and what happens as a sequence in a numbered list?

**Comment by MarioProjects** [comment] 2022-03-08 19:02
Sure, I will try :)

1. I follow the Next.js config steps with exactly the same steps described in the main README.
2. Connect my wallet with a WalletMultiButton component.
3. The wallet connects and the button modifies with the wallet info (wallet logo, in this case, Phantom, and the short version of wallet address)
4. The wallet button dropdown opens with the options of the -> `Copy Address`, `Change wallet`, `Disconnect`.
5. I got back the control of the application (we could say).

The problem is step 4. I don't know why that dropdown, as shown in the screenshot (https://ibb.co/Xtgb9Q2), is opening "alone". Could we manage to don't auto-open?

**Comment by jordansexton** [comment] 2022-03-09 01:54
I'm afraid I haven't seen this happen before. Could you link to a repo that contains the code that produces the issue? I'll try to test it out directly and see if I can find out what's going on.

**Comment by jordansexton** [comment] 2022-03-23 00:56
The screenshots shown indicate that there are customizations made to the application. Closing as I can't reproduce this in the [example](https://solana-labs.github.io/wallet-adapter/example/) starter project.

**Closed by jordansexton** 2022-03-23 00:56 UTC

**Comment by plasmare** [comment] 2022-04-14 09:34
Also having this issue without any customistaions

**Comment by shadeglare** [comment] 2022-09-03 16:32
The strange behaviour still exists. To reproduce it you have to activate the auto-connect property in the demo example.
