### ISSUE TITLE
Unable to sign transactions using Ledger Wallet and Phanthom

### ISSUE THREAD

**Issue by soroshansari** [solana-labs/wallet-adapter#797] opened 2023-06-20 14:43 UTC
Recently Ledger holders are no longer able to sign any transaction on our site. We are using the updated version of all related packages but still getting this error.

```
WalletSignTransactionError: TypeError: Cannot destructure property 'signature' of 'r' as it is undefined.
    at rH.tN [as signAllTransactions] (_app-f2275ef5d0fc4349.js:247:263514)
    at async Object.signAllTransactions (_app-f2275ef5d0fc4349.js:247:270690)
    at async av (_app-f2275ef5d0fc4349.js:247:198290)
    at async t (699-fdf86c6192d38063.js:1:24392)
```

**Packages**
```
"@solana/spl-token": "^0.3.7",
"@solana/wallet-adapter-base": "^0.9.22",
"@solana/wallet-adapter-react": "^0.15.32",
"@solana/wallet-adapter-react-ui": "^0.9.31",
"@solana/wallet-adapter-wallets": "^0.19.16",
"@solana/web3.js": "^1.76.0",
```

**Desktop**
- Browser: Chrome Version 114.0.5735.133 (Official Build) (arm64)
- Extention: Phantom Version 23.6.1
- Ledger Device: Nano S Plus, OS Version 1.1.0
- Ledger App: Solana (SOL) Version 1.4.1

**Comment by bfriel** [comment] 2023-06-20 18:03
Hi @soroshansari — do you mind sharing a URL where we can reproduce this? Also, can you double check that you've enabled blind signing on your ledger device?

**Comment by soroshansari** [comment] 2023-06-21 15:04
Hi @bfriel, you are right. The issue was because of the `blind signing` setting that had been turned off for some users, probably after a Frameware or Solana App upgrade on their Ledgers. But shouldn't the package throw a more user-friendly error when the blind signing has been turned off?

**Comment by jordansexton** [comment] 2023-06-30 18:56
Closing this issue since it's not a Wallet Adapter issue. I agree that the error could be more useful though!

**Closed by jordansexton** 2023-06-30 18:56 UTC
