### ISSUE TITLE
Error in @jnwng/walletconnect-solana after version bump

### ISSUE THREAD

**Issue by sohrab-** [solana-labs/wallet-adapter#565] opened 2022-09-15 14:10 UTC
**Describe the bug**

Trying to bump up 1 or 2-month-old worth of versions to the latest ones but encountering build errors.

**To Reproduce**

Update `package.json`:

```diff
-        "@solana/wallet-adapter-base": "^0.9.10",
+        "@solana/wallet-adapter-base": "^0.9.16",
-        "@solana/wallet-adapter-react": "^0.15.9",
+        "@solana/wallet-adapter-react": "^0.15.18",
-        "@solana/wallet-adapter-react-ui": "^0.9.12",
+        "@solana/wallet-adapter-react-ui": "^0.9.16",
-        "@solana/wallet-adapter-wallets": "^0.17.2",
+        "@solana/wallet-adapter-wallets": "^0.18.9",
```

It causes the following errors in the app:

```
ERROR in ./node_modules/@jnwng/walletconnect-solana/lib/esm/index.js 1:0-26
Module not found: Error: Can't resolve './adapter' in './node_modules/@jnwng/walletconnect-solana/lib/esm'
Did you mean 'adapter.js'?
BREAKING CHANGE: The request './adapter' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.

ERROR in ./node_modules/@jnwng/walletconnect-solana/lib/esm/index.js 2:0-25
Module not found: Error: Can't resolve './errors' in './node_modules/@jnwng/walletconnect-solana/lib/esm'
Did you mean 'errors.js'?
BREAKING CHANGE: The request './errors' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

**Additional context**

I am using CRA 5.x (TypeScript). I saw some old issues from around Jan/Feb 2022 that looked similar to my issue.
 
However, I had this all working till June 2022 and doing pretty minor version bumps so whatever has occurred has only happened in the last couple of months.

Also, I am getting errors very specific to a single dependency, rather than across the board (which was the case with the old issues due to misconfiguration):

```
└─┬ @solana/wallet-adapter-wallets@0.18.9
  └─┬ @solana/wallet-adapter-walletconnect@0.1.4
    └── @jnwng/walletconnect-solana@0.1.1
```

I am not even using that specific wallet in my application so not sure why it's not tree-shook? 🤷

**Comment by jordansexton** [comment] 2022-09-15 23:25
Looking into this.

**Comment by jordansexton** [comment] 2022-09-16 17:22
This will be fixed by https://github.com/jnwng/walletconnect-solana/pull/6 (we'll want to update the version used in the WalletConnect adapter here).

**Comment by jordansexton** [comment] 2022-09-16 17:42
FWIW, I personally haven't seen this issue in building any of the starter projects, including testing with the example. A workaround for now might be to use individual wallet packages instead of the `wallets` package if you're finding that your bundler is including things it shouldn't.

**Comment by sohrab-** [comment] 2022-09-20 04:46
Thanks, @jordansexton! Yep, that's what we're going to do since when I saw the size breakdown of the production bundle.

**Comment by jordansexton** [comment] 2022-09-20 18:40
If you're seeing packages you don't use not being tree shaken in your production bundle, that's definitely an issue on its own. Can you say more about what's happening?

**Comment by jordansexton** [comment] 2022-09-21 00:02
Published
+ @solana/wallet-adapter-walletconnect@0.1.6
+ @solana/wallet-adapter-wallets@0.19.0

**Comment by jordansexton** [comment] 2022-09-21 00:03
Please let me know if these don't fix it for you!

**Closed by jordansexton** 2022-09-21 00:02 UTC

**Comment by sohrab-** [comment] 2022-09-21 01:01
Re tree-shaking, this is what I'm seeing. I can raise a separate issue if you think this is to fix in this repo.

I run the following on this repo: https://github.com/labeleven-dev/bettercallsol

```
npm install
npm run build
npx source-map-explorer 'build/static/js/*.js'
```

![image](https://user-images.githubusercontent.com/4444588/191390348-3fb3ae1c-ab41-44f9-a741-7d60182cb9be.png)

As you can see, a few packages coming through, e.g. thicc boi `@blotco/sdk`. This is what I'm actually using:

https://github.com/labeleven-dev/bettercallsol/blob/60e71df986bea0e8d321fc674e7cc8047464fec1/src/components/common/Web3Provider.tsx#L33-L45

**Comment by jordansexton** [comment] 2022-09-23 23:15
> Re tree-shaking, this is what I'm seeing. I can raise a separate issue if you think this is to fix in this repo.

@sohrab- Please do (if it's something that's caused by this repo)! I'm not sure what would be causing it though.
