### ISSUE TITLE
Promise returned by disconnect function of useWallet does not settle

### ISSUE THREAD

**Issue by TigranHelio** [solana-labs/wallet-adapter#766] opened 2023-04-10 11:09 UTC
**Describe the bug**
When I call the disconnect function of useWallet hook with await, it stays in await forever. If I call it with promise.then, callback function will never be called. Interestingly, if you call disconnect twice, first promise will never settle, but the second one will.

**To Reproduce**
1. Connect phantom wallet 
2. Try to disconnect (`await disconnect()` or `disconnect().then(...)`)

**Expected behavior**
Wallet should disconnect, and promise should be settled

**Screenshots**
![image](https://user-images.githubusercontent.com/122271625/230889918-80943640-0013-454b-96aa-b528bd48f661.png)
![image](https://user-images.githubusercontent.com/122271625/230890124-797729d1-4882-424a-8a20-e82ad82f72cd.png)
P.S. signout function basically calls disconnect

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chrome Phantom extension
 - Version: 112.0.5615.49 (Chrome), 23.3.6 (Phantom)

**Additional context**
This issue happened recently, it was working fine before

**Comment by jordansexton** [comment] 2023-04-10 19:44
This is a duplicate of #755, which is an issue with Phantom, not Wallet Adapter. It's been fixed but users may need to manually update to the latest Phantom version. See https://github.com/solana-labs/wallet-adapter/issues/755#issuecomment-1502231199

**Closed by jordansexton** 2023-04-10 19:44 UTC
