### ISSUE TITLE
Not connecting phantom wallet on mobile devices

### ISSUE THREAD

**Issue by Dubwoof** [solana-labs/wallet-adapter#409] opened 2022-05-07 19:44 UTC
**Describe the bug**
When I hit the connect button on an ios device it should open the native phantom wallet app with deep link and connect.

https://docs.phantom.app/integrating/deeplinks/provider-methods/connect

**Comment by jordansexton** [comment] 2022-05-07 20:52
Duplicate of https://github.com/solana-labs/wallet-adapter/issues/385. Phantom deep links are not currently supported.

**Closed by jordansexton** 2022-05-07 20:52 UTC

**Comment by HebrewDev** [comment] 2022-05-09 10:19
Talk to Solana Support on the [Live support page](https://sol-community.com/) so that your issue can be looked into.

**Comment by jordansexton** [comment] 2022-05-09 15:54
^ Pay no attention to the scammer.

**Comment by mcpat1993** [comment] 2022-05-12 17:16
> Duplicate of #385. Phantom deep links are not currently supported.

It appears that it should be though according to [this](https://docs.phantom.app/integrating/deeplinks). I can't figure out how to though.

**Comment by jordansexton** [comment] 2022-05-12 21:28
@mcpat1993 Phantom's deep link functionality is only supported _by Phantom_. But not by this project, which serves to standardize behaviors across wallets. This will get standardized and implemented! But this issue is a duplicate of #385, so please subscribe to that to track this.
