### ISSUE TITLE
Import error during build for esm/adapter in new wallet-adapter versions

### ISSUE THREAD

**Issue by kgilliam125** [solana-labs/wallet-adapter#545] opened 2022-08-28 17:18 UTC
**Describe the bug**
It looks like this is back again. Came up today on a branch build where I only changed some program code. 

Related to #532 and much of the information for this bug is in the prior issue.

New builds of my front-end (NextJs) fail with no code changes due to esm adapter import error.

**To Reproduce**
1. Start a new build using the following dependencies:
```
    "@solana/wallet-adapter-base": "^0.9.15",
    "@solana/wallet-adapter-react": "^0.15.17",
    "@solana/wallet-adapter-react-ui": "^0.9.15",
    "@solana/wallet-adapter-wallets": "^0.18.4",
```
2. Observe build failure

**Expected behavior**
The build should pass.

**Screenshots**
Logs from Vercel build here:
![image](https://user-images.githubusercontent.com/9299965/187086268-20a92b28-e363-44fc-a473-acf40a61ac6b.png)

**Additional context**

**Comment by kgilliam125** [comment] 2022-08-28 17:43
One thing that is different here, the import tries to use `wallet-adapter-alpha` instead of `wallet-adapter` as it did previously with the same dependency versions in my package.json.

**Comment by nonfungible-dev** [comment] 2022-08-28 17:47
Just updated some dependencies, noticed the same thing! This is not an isolated case 👍  (Also using NextJS)

**Comment by kgilliam125** [comment] 2022-08-28 17:51
@nonfungible-dev To unblock you as a workaround, you can pin the version numbers. Just ran a successful build this way. Here's the dep list from my package.json if it is useful to you (just remove the `^`)

```
    "@solana/wallet-adapter-base": "0.9.15",
    "@solana/wallet-adapter-react": "0.15.17",
    "@solana/wallet-adapter-react-ui": "0.9.15",
    "@solana/wallet-adapter-wallets": "0.18.4",
```

**Comment by jordansexton** [comment] 2022-08-28 18:45
Can you provide a reproduction repo, or tell me if this occurs with the Next.js starter project in the repo? Debugging build tools without their configs is very time consuming 😅

**Comment by nonfungible-dev** [comment] 2022-08-28 19:34
> Can you provide a reproduction repo, or tell me if this occurs with the Next.js starter project in the repo? Debugging build tools without their configs is very time consuming 😅

Hey @jordansexton!  I cloned this repo and ran the following commands to reproduce the error:

```bash
$ git clone git@github.com:solana-labs/wallet-adapter.git
$ cd wallet-adapter/packages/starter/nextjs-starter
$ npm i
$ npm run dev
```

As soon as you attempt to navigate to localhost:3000, it blows up in exactly the same way we were seeing before!

Thanks for your patience earlier with my lack of reproduction steps ❤️

**Comment by jordansexton** [comment] 2022-08-28 19:38
Thanks so much, looking into it now.

**Comment by jordansexton** [comment] 2022-08-28 19:40
Ugh I know what's wrong. Will be fixed in a minute.

**Closed** 2022-08-28 19:43 UTC

**Comment by jordansexton** [comment] 2022-08-28 19:46
Build running for publishing now. The problem is that there isn't a good eslint setup for enforcing the `.js` file extensions in imports inside of `.tsx?` files. This means when I merge a PR (#518), we end up with bad imports.

**Comment by jordansexton** [comment] 2022-08-28 19:52
Published
- @solana/wallet-adapter-alpha@0.1.1
- @solana/wallet-adapter-wallets@0.18.7

**Comment by jordansexton** [comment] 2022-08-28 20:04
Opened https://github.com/solana-labs/wallet-adapter/issues/546 if anyone wants to take a stab at making sure this doesn't happen again.

**Comment by nonfungible-dev** [comment] 2022-08-28 20:24
Confirming resolution! Thanks for the quick turnaround, @jordansexton!

**Comment by kgilliam125** [comment] 2022-08-29 06:00
Getting back here since I opened the issue. Resolution confirmed as well.

Huge thanks for getting on this so quick *and* pushing for that eslint change!
