### ISSUE TITLE
Wallet Multi button disconnect error

### ISSUE THREAD

**Issue by prashantcrypto** [solana-labs/wallet-adapter#757] opened 2023-03-23 13:07 UTC
**Describe the bug**

the wallet multi button isnt working in the react or material ui after connecting

**Comment by mcintyre94** [comment] 2023-03-23 13:28
Are you using Phantom? Do you see the button change to "Disconnecting..." but not disconnect? This might be a dupe of https://github.com/solana-labs/wallet-adapter/issues/755

**Comment by jessupjn** [comment] 2023-03-23 17:19
I can confirm - I am not even using the wallet multi button, but rather calling `disconnect()` directly from `WalletContextState`.

Everything works as expected for Backpack / Solflare. Phantom doesn't disconnect successfully.

**Closed** 2023-03-23 19:58 UTC
