### ISSUE TITLE
Connection is undefined after connecting to wallet

### ISSUE THREAD

**Issue by keshrisohit** [solana-labs/wallet-adapter#36] opened 2021-08-30 06:53 UTC
I am able to retrieve the public Key as specified in Readme.MD but getting an error with the connection.
Unhandled Rejection (WalletSendTransactionError): connection is undefined

**Comment by exogenesys** [comment] 2021-08-30 13:14
+1

**Comment by jordansexton** [comment] 2021-08-30 16:09
Can you check to make sure the context is properly initialized? The reason I can think of for `connection` being undefined is that the `ConnectionProvider` perhaps wasn't added. If that's not the case, can you provide a reproduction of the issue?

```tsx
    return (
        <ConnectionProvider endpoint={endpoint}>
            <WalletProvider wallets={wallets} autoConnect>
                <WalletDialogProvider>
                    <WalletMultiButton/>
                    <WalletDisconnectButton/>
                </WalletDialogProvider>
            </WalletProvider>
        </ConnectionProvider>
    );
```

**Comment by jordansexton** [comment] 2021-08-31 15:54
Closing this issue for now, please reopen with steps to reproduce if your ConnectionProvider is configured and you're still experiencing this.

**Closed by jordansexton** 2021-08-31 15:54 UTC
