### ISSUE TITLE
Module '"@solana/wallet-adapter-wallets"' has no exported member 'getWallets'.

### ISSUE THREAD

**Issue by katopz** [solana-labs/wallet-adapter#217] opened 2021-12-21 12:08 UTC
**Describe the bug**
Module '"@solana/wallet-adapter-wallets"' has no exported member 'getWallets'.

**To Reproduce**
1. `yarn add @solana/wallet-adapter-base`
2. get `"@solana/wallet-adapter-wallets": "^0.13.0",`

**Expected behavior**
get `"@solana/wallet-adapter-wallets": "^0.13.1",`

**Desktop (please complete the following information):**
 - OS: macOS

**Additional context**
I can see version `0.13.1` github has `getWallets` but `0.13.0` didn't.
So I expect to see `0.13.1` release so I can import it.

Or maybe I just misunderstand something please enlight.

**Comment by kacemlight** [comment] 2021-12-21 16:18
The error while trying to download dependencies:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @solana/wallet-adapter-wallets@0.13.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

Can you please publish the @solana/wallet-adapter-wallets@0.13.1.

**Comment by jordansexton** [comment] 2021-12-21 17:39
Ah, the issue here is that the starter packages / docs are out of date with a few changes that have been made recently. This will be fixed today.

**Closed** 2021-12-21 17:49 UTC

**Comment by jordansexton** [comment] 2021-12-21 17:53
The issue is that the `getWallets` function was merged too soon -- there are some related changes still pending.

I've fixed the starter projects so they don't rely on the unpublished wallets package version.

Instead of using `getWallets` for now, do this:

```tsx
import {
    getLedgerWallet,
    getPhantomWallet,
    getSlopeWallet,
    getSolflareWallet,
    getSolletExtensionWallet,
    getSolletWallet,
    getTorusWallet,
} from '@solana/wallet-adapter-wallets';

// ...

    const wallets = useMemo(
        () => [
            getPhantomWallet(),
            getSlopeWallet(),
            getSolflareWallet(),
            getTorusWallet(),
            getLedgerWallet(),
            getSolletWallet({ network }),
            getSolletExtensionWallet({ network }),
        ],
        [network]
    );
```

See https://github.com/solana-labs/wallet-adapter#setup for more details.
