### ISSUE TITLE
Next.js 12: Cannot find module useWalletModal

### ISSUE THREAD

**Issue by stanleycyang** [solana-labs/wallet-adapter#246] opened 2022-01-06 06:02 UTC
**Describe the bug**
When deploying to production, I'm seeing this error happen: 
<img width="1028" alt="Screen Shot 2022-01-05 at 9 58 15 PM" src="https://user-images.githubusercontent.com/3037893/148336020-7df14dc7-93ec-4efb-b4c2-9b1cb6e5024d.png">

**To Reproduce**
1. Install the @solana/wallet-adapter-react-ui package in next.js
2. Set up the wallet connection
3. Use the WalletMultiButton
4. Refresh the page, and see the error. You can also see the error in deployment

**Expected behavior**
The `useWalletModal` should be provided

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 96

**Comment by jordansexton** [comment] 2022-01-06 07:02
Please check out the Next-based nextjs-starter project in the repo. There's also the example project that uses Next. The issue is very likely with your project configuration.

https://github.com/solana-labs/wallet-adapter#build-from-source

The steps here should help, just replace the last step with building the nextjs-starter project.

**Comment by stanleycyang** [comment] 2022-01-06 21:45
@jordansexton it looks like this example is broken on nextjs version 12.

**Comment by jordansexton** [comment] 2022-01-06 22:38
Thanks @stanleycyang! Would you be interested in opening a branch + PR to update the nextjs-starter and example starter projects to use Next 12?

**Comment by gpoole** [comment] 2022-01-07 01:35
Also having the same issue with a fresh project created with create-next-app 12.0.7 and using the sample code from this repo. From what I saw seemed to be caused by the .js extensions used in the esm versions. I tried changing one of the imports that was erroring from .js to .mjs and it was happy with that (just got another error about a different file so can't say 100% it fixes everything).

**Comment by jordansexton** [comment] 2022-01-07 02:14
@gpoole any chance you'd be willing to PR a change to cause the ESM builds to output mjs files and see if it fixes it?

**Comment by jordansexton** [comment] 2022-01-07 02:21
For anyone that needs a temporary workaround, please use the Next.js 11-based [starter project](https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/nextjs-starter).

**Comment by gpoole** [comment] 2022-01-07 02:52
I had a look at doing a PR for this @jordansexton, but it seems like the fix might be more general. I'd say that this issue is a specific instance of #241, but they're basically caused by the ESM strict resolution problem from what I can see.

**Comment by jordansexton** [comment] 2022-01-09 03:59
#254 will fix this when merged.

**Closed** 2022-01-11 02:40 UTC

**Comment by jordansexton** [comment] 2022-01-11 03:35
Published:
 - @solana/wallet-adapter-base@0.9.2
 - @solana/wallet-adapter-react@0.15.2
 - @solana/wallet-adapter-vue@0.4.3
 - @solana/wallet-adapter-example@0.18.0
 - @solana/wallet-adapter-nextjs-starter@0.8.0
 - @solana/wallet-adapter-ant-design@0.11.2
 - @solana/wallet-adapter-material-ui@0.16.2
 - @solana/wallet-adapter-react-ui@0.9.3
 - @solana/wallet-adapter-vue-ui@0.2.2
 - @solana/wallet-adapter-bitkeep@0.3.2
 - @solana/wallet-adapter-bitpie@0.5.2
 - @solana/wallet-adapter-blocto@0.5.2
 - @solana/wallet-adapter-clover@0.4.2
 - @solana/wallet-adapter-coin98@0.5.2
 - @solana/wallet-adapter-coinhub@0.3.2
 - @solana/wallet-adapter-ledger@0.9.2
 - @solana/wallet-adapter-mathwallet@0.9.2
 - @solana/wallet-adapter-phantom@0.9.2
 - @solana/wallet-adapter-safepal@0.5.2
 - @solana/wallet-adapter-slope@0.5.2
 - @solana/wallet-adapter-solflare@0.6.2
 - @solana/wallet-adapter-sollet@0.10.3
 - @solana/wallet-adapter-solong@0.9.2
 - @solana/wallet-adapter-tokenpocket@0.4.2
 - @solana/wallet-adapter-torus@0.11.3
 - @solana/wallet-adapter-wallets@0.14.2
