### ISSUE TITLE
Cannot find module @solana/wallet-adapter-base

### ISSUE THREAD

**Issue by Yusuf-Uluc** [solana-labs/wallet-adapter#534] opened 2022-08-22 01:30 UTC
**Describe the bug**
I am getting this error in the console when trying to connect to my nuxt 3 + vite.js app: 
```
ℹ Vite server warmed up in 122ms                                                                                                              03:18:43
ℹ Vite client warmed up in 3052ms                                                                                                             03:18:45
✔ Vite server built in 3497ms                                                                                                                 03:18:47
✔ Nitro built in 220 ms                                                                                                                 nitro 03:18:47
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'path_to_project/node_modules/@solana/wallet-adapter-base/lib/esm/adapter' imported from path_to_project/node_modules/@solana/wallet-adapter-base/lib/esm/index.js
    at new NodeError (node:internal/errors:387:5)
    at finalizeResolution (node:internal/modules/esm/resolve:404:11)
    at moduleResolve (node:internal/modules/esm/resolve:965:10)
    at defaultResolve (node:internal/modules/esm/resolve:1173:11)
    at nextResolve (node:internal/modules/esm/loader:173:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:852:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:439:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**To Reproduce**
1. Install the latest version of @solana/wallet-adapter-wallet (0.18.3) and @solana/wallet-adapter-base (0.9.14)
2. Run your Nuxt 3 App with the following vite config:
```
export default defineNuxtConfig({
  builder: "vite",
  ssr: true,
  css: ["assets/css/main.pcss"],
  postcss: {
    plugins: {
      tailwindcss: {},
      autoprefixer: {},
    },
  },
  build: {
    transpile: ["@headlessui/vue"],
  },

  typescript: {
    tsConfig: {
      esModuleInterop: true,
    },
  },
  vite: {
    plugins: [
      NodeGlobalsPolyfillPlugin({
        buffer: true,
        process: true,
      }),
      NodeModulesPolyfillPlugin(),
    ],
    esbuild: {
      target: "esnext",
      supported: { bigint: true },
      define: {
        global: "globalThis",
      },
    },
    optimizeDeps: {
      esbuildOptions: {
        target: "esnext",
        supported: { bigint: true },
        define: {
          global: "globalThis",
        },
      },
    },
    resolve: {
      alias: {
        "@": path.resolve(__dirname, "./"),
        // process: "process/browser",
        // stream: "stream-browserify",
        // zlib: "browserify-zlib",
        // util: "util",
      },
    },
  },
});
```

**Desktop (please complete the following information):**
 - OS: MacOS (M1)
 - Browser: Chrome

**Additional context**
The error suddenly appeared I haven't changed a single line of code that has to do something with the package it suddenly just stopped working. (I verified every change using gits version control and I didn't change any code).

I am only adding the wallets to the solana-wallet-vue configuration inside the **plugins/solana-wallet-vue.js** file. The solana-wallets-vue plugin worked just fine previously as well as in my other projects so I don't think it has to do something with that.

**Comment by jordansexton** [comment] 2022-08-22 01:34
Duplicate of #532, see https://github.com/solana-labs/wallet-adapter/issues/532#issuecomment-1221687443 for an alpha build with a fix to test out.

**Closed by jordansexton** 2022-08-22 01:34 UTC

**Comment by Yusuf-Uluc** [comment] 2022-08-22 01:43
@jordansexton Thank you so much you literally saved my day. Works like a charm

**Comment by jordansexton** [comment] 2022-08-22 01:44
Great! Please subscribe to that issue so you'll get notified when the production release is out.

**Comment by Yusuf-Uluc** [comment] 2022-08-22 01:45
Sure
