### ISSUE TITLE
Add support for encrypting ?

### ISSUE THREAD

**Issue by MathieuCesbron** [solana-labs/wallet-adapter#551] opened 2022-08-31 21:32 UTC
Hello, 

I am making a DAPP where I need to store sensitive data on-chain.  The sender would encrypt a message with the public key of the receiver. The receiver would be able to decrypt with his private key, so only him can do it.

I don't think it exists yet for Solana.

**Comment by jordansexton** [comment] 2022-08-31 21:38
Duplicate of https://github.com/solana-labs/wallet-adapter/issues/323, check out the comments there. This is planned to be implemented as part of the Wallet Standard, but Wallet Adapter can't support it until wallets do (and today, they don't).

**Closed by jordansexton** 2022-08-31 21:38 UTC

**Comment by iceomatic** [comment] 2023-01-01 22:26
Whats the current state of things concerning this? Any wallets supporting this yet?

**Comment by somali0128** [comment] 2023-05-18 14:33
+1

Any news of using Solana wallet to do the encryption work?
