### ISSUE TITLE
Create React App is broken by lack of default polyfills in Webpack 5

### ISSUE THREAD

**Issue by cogoo** [solana-labs/wallet-adapter#241] opened 2022-01-05 01:42 UTC
Edit by @jordansexton:

To anyone looking for a very good workaround right now, don't use Create React App. Just use the [react-ui-starter](https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/react-ui-starter) or [material-ui-starter](https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/material-ui-starter) projects with Parcel, or the [nextjs-starter](https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/nextjs-starter) project with Next.js, save yourself a huge hassle, and get much faster builds with SWC instead of Babel.

---

**Describe the bug**
Broken build with CRA v5, unable to resolve modules.

**To Reproduce**
1. Initialize a new CRA project. `npx create-react-app my-app-test`
2. Install and use any wallet-adapter packages
3. See error

```
BREAKING CHANGE: The request './adapter' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

**Solution**
Relative imports must include a file extension to follow ESM strict mode requirements introduced in Webpack 5. It's valid typescript to include `.js` extensions as part of the import path 🤯 :

example.ts

```typescript
import { Example } from './example.js';
```
compiles to

example.js
```javascript
import { Example } from './example.js';
```

**Comment by jordansexton** [comment] 2022-01-05 03:54
It's worth noting that `yarn lint` is also currently broken.

**Comment by jordansexton** [comment] 2022-01-05 03:55
I discovered this when I started working on adding check for import extensions to eslint: https://github.com/solana-labs/wallet-adapter/commit/7b443655c9b8c196fa952a9cf904ba1e200f3e9d

**Comment by metallicalfa** [comment] 2022-01-05 04:18
I am facing similar issues in /packages/starter/react-ui-starter. 

```
/Users/labstorus/Documents/github/torus/wallet-adapter/packages/core/base/lib/esm/signer.js 19:16
Module parse failed: Unexpected token (19:16)
File was processed with these loaders:
 * ../../../node_modules/react-scripts/node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ../../../node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|           ...sendOptions
|         } = options;
>         signers?.length && transaction.partialSign(...signers);
|         transaction = await this.signTransaction(transaction);
|         const rawTransaction = transaction.serialize();
```

**Comment by cogoo** [comment] 2022-01-05 15:47
Recommended solution seems to be:

> You must use a .js extension in relative imports even though you're importing .ts files.

Full breakdown: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by cogoo** [comment] 2022-01-05 16:14
> It's worth noting that `yarn lint` is also currently broken.

🧐 this is unrelated. Fixed this by removing `react-app/jest` from `material-ui-starter/package.json` and `react-ui-starter/package.json`

```diff
 "eslintConfig": {
        "extends": [
             "react-app",
-            "react-app/jest"
        ]
    },
```

**Comment by Eliascm17** [comment] 2022-01-05 17:43
I'm experiencing this in a CRA v5 app as well. 
<img width="1126" alt="Screen Shot 2022-01-05 at 11 42 09 AM" src="https://user-images.githubusercontent.com/20745708/148263797-9cadd625-b624-4a56-8338-202b824f5eb8.png">

**Comment by Malai237** [comment] 2022-01-05 18:01
I am facing the same issues and I am using node

**Comment by dan-garay** [comment] 2022-01-05 20:16
Need to fix this asap

**Comment by jordansexton** [comment] 2022-01-06 02:40
Linting and the starter projects are fixed thanks to @cogoo in #245.

This issue is otherwise blocked until Craco fully supports CRA 5 / Webpack 5 and we can configure Webpack to build with ESM modules that don't use .mjs extensions.

Until then, please use one of the [starter projects](https://github.com/solana-labs/wallet-adapter#starter-projects) that use Next.js or CRA 4. They work right now and don't require additional configuration.

Instructions to run the React UI + CRA4 starter project are here:
https://github.com/solana-labs/wallet-adapter#build-from-source

**Comment by kevinforrestconnors** [comment] 2022-01-06 04:27
> 

Any recommendation to those who have already started a project?  I'd rather not remake my project and just want to fix this to continue working

**Comment by jordansexton** [comment] 2022-01-06 04:33
Nope, there's no good workaround at this time, sorry. CRA 5 is not supported.

**Comment by jordansexton** [comment] 2022-01-06 04:34
It's relatively straightforward to take your code from your CRA 5 app and drop it into the CRA 4 based react-ui-starter project though.

**Comment by kevinforrestconnors** [comment] 2022-01-06 06:33
> 

fair enough, thanks

**Comment by Malai237** [comment] 2022-01-06 15:10
Hey guys, I got it to work. I uninstalled the libraries listed below and downloaded them again with these specific versions: 
"@solana/wallet-adapter-base": "^0.7.1",
"@solana/wallet-adapter-react": "^0.13.1",
"@solana/wallet-adapter-react-ui": "^0.6.1",
"@solana/wallet-adapter-wallets": "^0.11.3",
"@solana/web3.js": "^1.31.0",
...
"react-scripts": "4.0.3",

**Comment by jordansexton** [comment] 2022-01-06 15:30
@Malai237 you don't need to downgrade the packages to get this to work with CRA 4. The react-ui-starter project works out of the box with the latest versions of the packages using CRA 4.

**Comment by jordansexton** [comment] 2022-01-06 18:27
Just published:
 - @solana/wallet-adapter-base@0.9.1
 - @solana/wallet-adapter-react@0.15.1
 - @solana/wallet-adapter-vue@0.4.2
 - @solana/wallet-adapter-example@0.17.1
 - @solana/wallet-adapter-material-ui-starter@0.12.1
 - @solana/wallet-adapter-nextjs-starter@0.7.1
 - @solana/wallet-adapter-react-ui-starter@0.8.1
 - @solana/wallet-adapter-ant-design@0.11.1
 - @solana/wallet-adapter-material-ui@0.16.1
 - @solana/wallet-adapter-react-ui@0.9.1
 - @solana/wallet-adapter-vue-ui@0.2.1
 - @solana/wallet-adapter-bitkeep@0.3.1
 - @solana/wallet-adapter-bitpie@0.5.1
 - @solana/wallet-adapter-blocto@0.5.1
 - @solana/wallet-adapter-clover@0.4.1
 - @solana/wallet-adapter-coin98@0.5.1
 - @solana/wallet-adapter-coinhub@0.3.1
 - @solana/wallet-adapter-ledger@0.9.1
 - @solana/wallet-adapter-mathwallet@0.9.1
 - @solana/wallet-adapter-phantom@0.9.1
 - @solana/wallet-adapter-safepal@0.5.1
 - @solana/wallet-adapter-slope@0.5.1
 - @solana/wallet-adapter-solflare@0.6.1
 - @solana/wallet-adapter-sollet@0.10.2
 - @solana/wallet-adapter-solong@0.9.1
 - @solana/wallet-adapter-tokenpocket@0.4.1
 - @solana/wallet-adapter-torus@0.11.2
 - @solana/wallet-adapter-wallets@0.14.1
 
 These packages include #245 and should work with CRA4 / Craco.

**Comment by kevinforrestconnors** [comment] 2022-01-06 19:27
> Instructions to run the React UI + CRA4 starter project are here:
> https://github.com/solana-labs/wallet-adapter#build-from-source

I was not able to get the starter projects to work.

Since there is a parent directory to the `src` directory, nothing works if you build the project and then move the `src` to your other project.  I don't want all the other stuff - literally just the front end app is what I want.

For example:

The instructions in https://github.com/solana-labs/wallet-adapter#build-from-source 

Clone the project:
```
git clone https://github.com/solana-labs/wallet-adapter.git
```
Install dependencies:
```
cd wallet-adapter
yarn install
```
Build all packages:
```
yarn build
```
Run locally:
```
cd packages/starter/react-ui-starter
yarn start
```

Then I moved the `react-ui-starter` folder to my app, and it does not work, since it is dependent on the parent folder's `node_modules`

**Comment by kevinforrestconnors** [comment] 2022-01-06 20:51
> @Malai237 you don't need to downgrade the packages to get this to work with CRA 4. The react-ui-starter project works out of the box with the latest versions of the packages using CRA 4.

I can't even get this to work with CRA 4.  Jest tests break:

```
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from './useWalletModal';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'
```

**Comment by kevinforrestconnors** [comment] 2022-01-06 21:17
So I have learned that the issue is specifically with `WalletModalProvider` breaking jest tests, even with CRA 4.  I have decided to just not use it and make my own UI.

**Comment by jordansexton** [comment] 2022-01-06 21:58
> Then I moved the `react-ui-starter` folder to my app, and it does not work, since it is dependent on the parent folder's `node_modules`

This is because of Lerna + Yarn workspaces linking the dependencies locally.

If you move `react-ui-starter` out of the project directory, run `yarn install` from the `react-ui-starter` directory. This should install the dependencies locally in the `node_modules` of that directory instead of hoisting them.

**Comment by jordansexton** [comment] 2022-01-06 22:01
> Jest tests break

What tests are you running? The only Jest tests that ship with this project right now are in the React package. This shouldn't affect your starter project running, right?

**Comment by jordansexton** [comment] 2022-01-06 22:04
As for the Jest tests that ship with the React package, they run and pass:

```
➜  react git:(master) yarn test
yarn run v1.22.17
$ jest
...
Test Suites: 2 passed, 2 total
Tests:       45 passed, 45 total
Snapshots:   0 total
Time:        6.412 s
Ran all test suites.
✨  Done in 7.91s.
```

**Comment by jordansexton** [comment] 2022-01-06 22:06
> If you move `react-ui-starter` out of the project directory, run `yarn install` from the `react-ui-starter` directory.

I just did this and it works.

**Comment by jordansexton** [comment] 2022-01-06 22:08
Perhaps we should configure the starter projects to disable hoisting since they are supposed to run standalone. Comes at the expense of initial install time, but maybe worthwhile?

cc @cogoo

**Comment by gpoole** [comment] 2022-01-07 01:26
Just to add my experience, the packages don't work with the latest Next.js version (12.0.7) in a project I created via CNA. Downgrading to Next.js 11 as used in the starter seems to have worked though. Next.js now uses SWC instead of webpack by default, so might this also be part of the problem? I'm not familiar with the details at all so please forgive me if this is a dumb question, but it seems like using mjs extensions for the esm exports has the broadest compatibility and resolves the issue, so is there a reason not to do that?

**Comment by jordansexton** [comment] 2022-01-07 01:30
@gpoole https://github.com/solana-labs/wallet-adapter/issues/246 is probably related to the Next.js issue. I'm also not familiar with it and haven't tested with Next 12.

> it seems like using mjs extensions for the esm exports has the broadest compatibility and resolves the issue, so is there a reason not to do that?

@cogoo you spent a good bit of time trying out different builds, wdyt?

**Comment by cogoo** [comment] 2022-01-07 01:40
> @gpoole #246 is probably related to the Next.js issue. I'm also not familiar with it and haven't tested with Next 12.
> 
> > it seems like using mjs extensions for the esm exports has the broadest compatibility and resolves the issue, so is there a reason not to do that?
> 
> @cogoo you spent a good bit of time trying out different builds, wdyt?

It looks like most bundlers are now enforcing strict ESM imports which are where the errors occur. To my knowledge the `.mjs` extension wouldn't help since the ESM build is picked up correctly. The issue is that we are not using full file paths for imports.

i.e. `import { someModule } from './module` needs to be `import { someModule } from './module.js`

**Comment by gpoole** [comment] 2022-01-07 01:48
I've mentioned this on #246 but I noticed in Next.js 12 just changing the extension to .mjs seemed to be enough. It looks like Next or maybe SWC is using [esm loader](https://github.com/standard-things/esm) which does say about its strict mode:

> "strict" to treat only .mjs files as ESM.

So maybe that's it, or maybe I'm misreading. Looking around I noticed the [Webpack docs](https://webpack.js.org/guides/ecma-script-modules/) say:

> Imports in ESM are resolved more strictly. Relative requests must include a filename and file extension.

And the [Node docs](https://nodejs.org/api/esm.html#mandatory-file-extensions) also say:

> A file extension must be provided when using the import keyword to resolve relative or absolute specifiers. Directory indexes (e.g. './startup/index.js') must also be fully specified.

I wasn't familiar with this change. Sorry for the diversion!

**Comment by gpoole** [comment] 2022-01-07 03:00
I didn't originally understand [your earlier comment](https://github.com/solana-labs/wallet-adapter/issues/241#issuecomment-1005842429) about using ".js" for imports in ".ts" files @cogoo but now I realised [that's the formal decision on how this is handled by TypeScript](https://www.typescriptlang.org/docs/handbook/esm-node.html):

>  [code] will have to be rewritten to use the extension of the output of foo.ts - so bar.ts will instead have to import from ./foo.js.

I thought it was going to be fixed by a compiler option or something. Strange!

**Comment by jordansexton** [comment] 2022-01-07 03:03
Unfortunately we tried changing the source code to do this, and it has a number of problems we don't have a good solution to yet. I think a better solution may be to find a way to output .mjs files in the ESM build, and also reference those extensions in the build, without modifying the TS source.

**Comment by jordansexton** [comment] 2022-01-07 03:11
https://www.npmjs.com/package/typescript-esm looks promising

**Comment by cogoo** [comment] 2022-01-07 07:59
> https://www.npmjs.com/package/typescript-esm / https://github.com/kristoferbaxter/typescript-esm looks promising
> 
> > When you add the tsc-esm compiler following the conclusion of TypeScript's output, this compiler will remap all generated files to use '.mjs' extensions for locally resolved items and rename every output's extension to '.mjs'.
> 
> Sounds like what we want?

This looks like it will do the job! I'll play around with this today

**Comment by cogoo** [comment] 2022-01-08 14:32
> https://www.npmjs.com/package/typescript-esm / https://github.com/kristoferbaxter/typescript-esm looks promising
> 
> > When you add the tsc-esm compiler following the conclusion of TypeScript's output, this compiler will remap all generated files to use '.mjs' extensions for locally resolved items and rename every output's extension to '.mjs'.
> 
> Sounds like what we want?

Experimented with this. Unfortunately, it doesn't work out of the box. After installing the package, the `lerna build` script fails on the `packages/starter/example` repository;

```shell
lerna ERR! yarn run build exited 1 in '@solana/wallet-adapter-example'
lerna ERR! yarn run build stdout:
$ yarn clean && next build && next export
$ shx rm -rf .next out
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types...
info  - Creating an optimized production build...
info  - Using external babel configuration from /Users/cogoo/LocalHost/GitHub/solana_projects/wallet-adapter/packages/starter/example/.babelrc.js
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build stderr:
Failed to compile.

ModuleNotFoundError: Module not found: Error: Can't resolve '@solana/wallet-adapter-react-ui' in '/Users/cogoo/LocalHost/GitHub/solana_projects/wallet-adapter/packages/starter/example/pages'


> Build error occurred
```

I'll be more comfortable adding the extension manually (prebuild) as that's the accepted convention.

https://www.typescriptlang.org/docs/handbook/esm-node.html

**Comment by jordansexton** [comment] 2022-01-08 16:35
I've seen that build error before, I don't know that it's related to this or unresolvable.

For the reasons we discussed before, I'm not comfortable with adding the extension to the source. It increases maintenance burden and eslint doesn't work for it yet. I'm also not convinced yet that this is a reasonable convention to follow when I haven't seen it used a single time in the wild.

I'll pick this up and work on it today.

**Comment by jordansexton** [comment] 2022-01-09 03:59
#254 will fix this when merged.

**Comment by jordansexton** [comment] 2022-01-11 03:39
Published:
 - @solana/wallet-adapter-base@0.9.2
 - @solana/wallet-adapter-react@0.15.2
 - @solana/wallet-adapter-vue@0.4.3
 - @solana/wallet-adapter-example@0.18.0
 - @solana/wallet-adapter-nextjs-starter@0.8.0
 - @solana/wallet-adapter-ant-design@0.11.2
 - @solana/wallet-adapter-material-ui@0.16.2
 - @solana/wallet-adapter-react-ui@0.9.3
 - @solana/wallet-adapter-vue-ui@0.2.2
 - @solana/wallet-adapter-bitkeep@0.3.2
 - @solana/wallet-adapter-bitpie@0.5.2
 - @solana/wallet-adapter-blocto@0.5.2
 - @solana/wallet-adapter-clover@0.4.2
 - @solana/wallet-adapter-coin98@0.5.2
 - @solana/wallet-adapter-coinhub@0.3.2
 - @solana/wallet-adapter-ledger@0.9.2
 - @solana/wallet-adapter-mathwallet@0.9.2
 - @solana/wallet-adapter-phantom@0.9.2
 - @solana/wallet-adapter-safepal@0.5.2
 - @solana/wallet-adapter-slope@0.5.2
 - @solana/wallet-adapter-solflare@0.6.2
 - @solana/wallet-adapter-sollet@0.10.3
 - @solana/wallet-adapter-solong@0.9.2
 - @solana/wallet-adapter-tokenpocket@0.4.2
 - @solana/wallet-adapter-torus@0.11.3
 - @solana/wallet-adapter-wallets@0.14.2
 
These packages now have strict ESM exports (.mjs files). This fixes Next.js 12-based projects which use Webpack 5 with strict ESM imports. 
 
It doesn't fix CRA 5-based projects because of a semi-related issue: Webpack 5 doesn't include polyfills for Node.js APIs by default, so it breaks with `buffer` and `crypto` imports.

Even though this issue was about strict ESM imports, I'll leave it open until CRA projects work.

**Comment by jordansexton** [comment] 2022-01-11 03:40
To anyone looking for a very good workaround right now, don't use Create React App. Just use the nextjs-starter project, save yourself a huge hassle, and get even faster builds with SWC instead of Babel.

**Comment by jordansexton** [comment] 2022-01-15 02:19
The react-ui-starter and material-ui-starter projects have been updated to use Parcel instead of CRA.

**Comment by steveluscher** [comment] 2022-01-16 06:36
Can anyone having trouble with the Solana wallet adapter and Create React App 5 patch in #264 and let me know if that solves your build issues? If you find another missing module, let me know what it is (paste in the build failure message if possible).

cc/ @cogoo, @Eliascm17, @Malai237, @dan-garay, @kevinforrestconnors

**Comment by steveluscher** [comment] 2022-01-16 07:45
It appears as though the CRA team's position is pretty clear: if we depend on a package and that package is designed to work in the browser, then they must produce a browser build that does not depend on Node APIs.

Read more about this here: https://github.com/facebook/create-react-app/issues/11756#issuecomment-996464456

In the meantime, some are suggesting to monkey patch your CRA5 Webpack config using `react-app-rewired` to add the Node polyfills back: https://github.com/facebook/create-react-app/issues/11756#issuecomment-1013246173. This is slightly less nuclear an option than ejecting from CRA or downgrading to CRA4.

**Comment by jordansexton** [comment] 2022-01-19 00:35
Thanks for digging into this @steveluscher. I think react-app-rewired for now, or Craco [once it supports CRA 5](https://github.com/gsoft-inc/craco/issues/378), is probably the way to go.

To anyone following this issue, my current recommendation is still just to use Parcel if you want something quick and lightweight (e.g. without server side rendering, which most dapps don't need), or Next.js if you want something heavier (SSR, API functions, etc.)

I realize that's not very satisfying, but unless you are already using some of the distinctive features of CRA like service workers, Jest, etc. you may not need it right away, and a simpler tool can help you build what you want.

**Comment by jordansexton** [comment] 2022-01-19 21:51
Any volunteers want to try out @steveluscher's promising solution @ https://github.com/solana-labs/wallet-adapter/pull/264#issuecomment-1015981946

Would love to know if this works for more people!

**Comment by dewittalex** [comment] 2022-01-20 01:23
> Any volunteers want to try out @steveluscher's promising solution @ [#264 (comment)](https://github.com/solana-labs/wallet-adapter/pull/264#issuecomment-1015981946)
> 
> Would love to know if this works for more people!

I'd be more than happy to test this, but I'm a bit ignorant to how. After I create-react-app, how do I install Steven's packages instead of "yarn add @solana/wallet-adapter-base ... etc." ?

**Comment by jordansexton** [comment] 2022-01-20 01:28
@dewittalex thanks! @steveluscher probably has better advice than me, but I think if you build his branch from source and then locally reference the packages from your CRA app, it might work.

Maybe something like `"@solana/wallet-adapter-react": "file:/../wallet-adapter/packages/core/react"` for all the relevant packages you depend on?

And then you might want to use https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/ or something to make sure that the internal dependencies also resolve to those since the directory structure will be a bit weird.

**Comment by jordansexton** [comment] 2022-01-20 01:29
Another option, actually -- stick your CRA package inside the `starters` directory of his branch after building it from source. Then you can run `yarn` from the base directory, and it should link your local dependencies without all that mess.

**Comment by steveluscher** [comment] 2022-01-20 02:07
You can link _local_ NPM packages and use them as though they're the published versions. See if you can get something like this working:

```
# Check out and build my PR
git clone https://github.com/steveluscher/wallet-adapter.git
cd wallet-adapter
git checkout polyfill-node-apis-for-webpack-5
yarn install && yarn build

# Link my PR's versions into your package manager
(cd packages/wallets/ledger && yarn link)
(cd packages/wallets/torus && yarn link)
```

Then go back to your project…

```
cd myproject
# Use the linked versions of these packages in your project
yarn link @solana/wallet-adapter-ledger
yarn link @solana/wallet-adapter-torus
```

And try to build.

You can unlink everything when you're done. Make sure to follow the instructions that appear.

```
yarn unlink @solana/wallet-adapter-ledger
yarn unlink @solana/wallet-adapter-torus
```

**Comment by steveluscher** [comment] 2022-01-20 02:45
> …or if yarn link doesn't understand how to propagate that package.json dependency down to the main project.

I sort of suspect that's true: https://github.com/yarnpkg/yarn/issues/2914#issuecomment-358055934

Maybe we should #yolo merge this, publish it, and see?

**Comment by jordansexton** [comment] 2022-01-20 03:41
Published:
 - @solana/wallet-adapter-ledger => 0.9.3
 - @solana/wallet-adapter-torus => 0.11.4
 
 Using these dependencies should fix the polyfill / CRA problems with no additional config required.
 
 Huge thanks to @steveluscher for his heroic effort debugging and fixing this both here and in upstream projects.

**Comment by jordansexton** [comment] 2022-01-20 03:42
(And if this doesn't fix all the CRA issues, at least we're a bit closer)

**Comment by jordansexton** [comment] 2022-01-20 04:51
Reopened -- #264 has been reverted by #275. It looks like the polyfills may be breaking the Next and Parcel starters.

**Comment by jordansexton** [comment] 2022-01-20 14:11
> Maybe we should #yolo merge this, publish it, and see?

@steveluscher lol

**Comment by TomLisankie** [comment] 2022-01-24 18:59
@jordansexton What's holding #276 back from being merged in? I'm trying to do work in a repo where my coworkers and I are using Webpack 5 and this is blocking us from moving forward. There are manual fixes that we've tried that work but those are not satisfactory for shipping of course.

**Comment by jordansexton** [comment] 2022-01-24 22:27
@TomLisankie thanks for understanding. #276 just needs to be tested before merging (I rushed to publish its predecessor #264 and broke all the packages) and I haven't had time to test it yet.

**Comment by TomLisankie** [comment] 2022-01-25 14:56
> @TomLisankie thanks for understanding. #276 just needs to be tested before merging (I rushed to publish its predecessor #264 and broke all the packages) and I haven't had time to test it yet.

Got it, thanks.

**Comment by ieow** [comment] 2022-01-28 09:22
Anyone have issue with latest wallet adapter with cra 4.0 ?
I am trying clone https://github.com/exiled-apes/candy-machine-v2-mint
then replace the wallet adapter with  "@solana/wallet-adapter-wallets": "^0.14.2" 
and hit error below when run npm start

```
./node_modules/@solana/wallet-adapter-wallets/lib/esm/adapters.mjs
Can't import the named export 'BitKeepWalletAdapter' from non EcmaScript module (only default export is available)
```

**Comment by nice-chute** [comment] 2022-01-30 17:20
been a month of not being able to properly use this

**Comment by nice-chute** [comment] 2022-01-30 17:25
Can someone please document what the correct work around would be?

**Closed** 2022-01-31 03:21 UTC
Labels: bug

**Comment by steveluscher** [comment] 2022-01-31 03:28
> Anyone have issue with latest wallet adapter with cra 4.0 ?

See #265!

**Comment by jordansexton** [comment] 2022-01-31 04:00
Published:

 - @solana/wallet-adapter-react => 0.15.3
 - @solana/wallet-adapter-example => 0.18.1
 - @solana/wallet-adapter-material-ui-starter => 0.13.1
 - @solana/wallet-adapter-nextjs-starter => 0.8.1
 - @solana/wallet-adapter-react-ui-starter => 0.9.2
 - @solana/wallet-adapter-ant-design => 0.11.3
 - @solana/wallet-adapter-material-ui => 0.16.4
 - @solana/wallet-adapter-react-ui => 0.9.5
 - @solana/wallet-adapter-bitkeep => 0.3.3
 - @solana/wallet-adapter-blocto => 0.5.3
 - @solana/wallet-adapter-clover => 0.4.3
 - @solana/wallet-adapter-coin98 => 0.5.3
 - @solana/wallet-adapter-coinhub => 0.3.3
 - @solana/wallet-adapter-ledger => 0.9.5
 - @solana/wallet-adapter-mathwallet => 0.9.3
 - @solana/wallet-adapter-safepal => 0.5.3
 - @solana/wallet-adapter-slope => 0.5.3
 - @solana/wallet-adapter-solflare => 0.6.3
 - @solana/wallet-adapter-solong => 0.9.3
 - @solana/wallet-adapter-tokenpocket => 0.4.3
 - @solana/wallet-adapter-torus => 0.11.6
 - @solana/wallet-adapter-wallets => 0.14.3
 
 Please try these packages using CRA 5! And huge thanks to @steveluscher for your tireless work on this.

**Comment by matanwrites** [comment] 2022-02-03 08:03
Amazing! Thanks

**Comment by jordansexton** [comment] 2022-02-07 00:38
This is fixed via #299 but you'll need to use react-app-rewired with config here to do the polyfills correctly. See the new [create-react-app-starter](https://github.com/solana-labs/wallet-adapter/tree/master/packages/starter/create-react-app-starter) project. The key parts are the [config-overrides.js](https://github.com/solana-labs/wallet-adapter/blob/master/packages/starter/create-react-app-starter/config-overrides.js) file and [`npm:process`](https://github.com/solana-labs/wallet-adapter/blob/f8a2f99a1a77f34cdff49c7ca0effc6fe8477f21/packages/starter/create-react-app-starter/package.json#L23) dependency.

The core issue is that the Torus and Ledger JS libraries don't correctly polyfill and incorrectly use globals, and this isn't handled by Webpack 5 without additional configuration, which you can't add with CRA5 alone. We use react-app-rewired to override, as Craco doesn't support CRA5 yet.

Published:
 - @solana/wallet-adapter-ledger@0.9.7
 - @solana/wallet-adapter-torus@0.11.9
 - @solana/wallet-adapter-wallets@0.15.3

**Comment by scottwilson312** [comment] 2022-02-10 20:20
@jordansexton  thanks for all of this. I took my CRA project and just copied over the releveant parts from the package.json (devDependencies) and config.json into my existing project and all is well

**Comment by Sunnyjson** [comment] 2022-02-24 07:09
I got the error message

`./node_modules/@solana/wallet-adapter-wallets/lib/esm/adapters.mjs
Can't import the named export 'BitKeepWalletAdapter' from non EcmaScript module (only default export is available)`

Sorry I didn't find the right solution，Tried the upgrade version to no avail， Can someone tell me how to fix it， thanks

**Comment by asifmuhammad** [comment] 2023-01-19 12:35
**Did anyone manage to fix this issue?**

./node_modules/@netless/window-manager/dist/index.mjs
Can't import the named export 'AnimationMode' from non EcmaScript module (only default export is available)

**Comment by L-F-Escobar** [comment] 2024-05-22 23:11
working with solana has been the worst experience of my programming life
