### ISSUE TITLE
Transaction fails on 0.15.4 works on 0.15.3 via Phantom

### ISSUE THREAD

**Issue by heldrida** [solana-labs/wallet-adapter#333] opened 2022-02-24 23:49 UTC
**Describe the bug**

By using the wallet-adapter to create and send a transaction an error occurs:

```
Phantom - RPC Error: Transaction creation failed
Object { code: -32003, message: "Transaction creation failed." }
```

By testing the transaction in the scaffold app ( https://github.com/solana-dev-adv/solana-dapp-next ) it works.

So by checking the diff noticed it uses 0.15.3 and not 0.15.4. I made a lot of tests and required two last tests to confirm if the issue is related to the network Testnet vs Devnet or the package version. Unfortunately hit the rate limit in the nodes and seems that I'm banned.

To understand the process check the discussion in:
Check the thread in https://discord.com/channels/428295358100013066/517163444747894795/946550026983837776

Where @lisenmayben  participated, thank for the time by the way!

**To Reproduce**

Copy the suggested transaction source in the docs and switch the wallet-adapter to 0.15.3 on latest phantom.

**Expected behavior**

**Screenshots**

<img width="621" alt="Screenshot 2022-02-24 at 03 10 06" src="https://user-images.githubusercontent.com/236752/155626496-4e1cff6d-07b5-4fee-a5c4-1abf5501da6e.png">

<img width="573" alt="Screenshot_2022-02-24_at_23 34 05" src="https://user-images.githubusercontent.com/236752/155627227-bf9a8645-93f9-49f7-8f4d-ba19a081f119.png">

**Desktop (please complete the following information):**
 - OS: macos monterey
 - Browser brave
 - Version latest

**Additional context**

I could've reached a conclusion but the rate limit really killed it and now I'm banned and can't even work...

**Comment by jordansexton** [comment] 2022-02-27 00:12
I'm closing this since it sounds unrelated to wallet-adapter, and is perhaps related to sending your transaction on the wrong cluster. But if you can provide a succinct, complete reproduction I'm happy to take a look.

**Closed by jordansexton** 2022-02-27 00:12 UTC
