### ISSUE TITLE
Wallet (Phantom) does not connect for some users

### ISSUE THREAD

**Issue by eeebad** [solana-labs/wallet-adapter#852] opened 2023-12-04 11:20 UTC
**Describe the bug**

I've encountered reports from multiple users who are experiencing difficulty connecting their wallets. While I haven't been able to reproduce the issue personally, some users mention that after selecting a wallet from the modal listing available options, nothing further occurs – it seems the extension popup fails to appear.

**Desktop:**
 - Browser [e.g. chrome, firefox, safari]

**Comment by jordaaash** [comment] 2023-12-04 18:23
Duplicate of https://github.com/solana-labs/wallet-adapter/issues/853

**Closed by jordaaash** 2023-12-04 18:23 UTC
