### ISSUE TITLE
Del fallback for phantom

### ISSUE THREAD

**Issue by Tataklim** [solana-labs/wallet-adapter#556] opened 2022-09-08 11:37 UTC
Hi! 
There was a [pr](https://github.com/solana-labs/wallet-adapter/pull/472) with fix for phantom adapter. This pr has solved an error of collision some wallets with phantom
But I've noticed, that a couple of weeks ago fallback to previous value [was added](https://github.com/solana-labs/wallet-adapter/commit/5a274e0a32c55d4376d63a802f0d512947b087af). So collisions came back :(
Could you help please, why was the fallback added? Phantom developers said that there is [no need](https://github.com/solana-labs/wallet-adapter/pull/472#issuecomment-1189275848) to have this fallback.

**Comment by jordansexton** [comment] 2022-09-08 22:11
Can you describe what error this causes specifically and who is affected by it? The bug report template in the repo exists to gather this detail.

Wallets colliding within the same namespace is something we can't solve without changing how wallets attach to the window, which is a major focus of the ongoing work here:

https://github.com/wallet-standard/wallet-standard/tree/master/packages/core/standard#present-a-predictable-interface-for-wallets-to-attach-to-the-window

**Comment by Tataklim** [comment] 2022-09-09 09:52
Hey hey @jordansexton 
I haven't created a bug report cause I am not sure is it exactly a bug or a feature :)
I understand the problem of collision and know that nowadays we can't solve it. I am just saying about the fact that Phantom writes his data both to `window.solana` and to `window.phantom.solana`. Some of wallets tries to overwrite just `window.solana`. So deleting fallback [here](https://github.com/solana-labs/wallet-adapter/commit/5a274e0a32c55d4376d63a802f0d512947b087af) at least could help avoid this collisions. But of course it doesn't solve the fundamental problem.

 
   **----Describe the bug**
Have MathWallet (or Coin98, or Exodus or some other) extension in browser.
**Don't** have installed Phantom extension in browser
Getting PhantomWalletAdapter.readyState === WalletReadyState.Installed
Because of [this](https://github.com/solana-labs/wallet-adapter/blob/master/packages/wallets/phantom/src/adapter.ts#L78) fallback

**----Expected behavior**
Getting PhantomWalletAdapter.readyState === WalletReadyState.NotDetected

**----Screenshots**
<img width="314" alt="image" src="https://user-images.githubusercontent.com/36628483/189321850-5a5c4062-9588-4a03-a3de-afec845bb8d3.png">

**Comment by jordansexton** [comment] 2022-09-09 16:56
Ah, this is (unfortunately) intended behavior. If a user has a wallet that's cloned the Phantom API, and doesn't have Phantom installed, it's better to let them connect than give them no options.

This is a short-term stopgap until we can standardize how wallets attach to the window, which is being done here: https://github.com/wallet-standard/wallet-standard/tree/master/packages/core/standard#present-a-predictable-interface-for-wallets-to-attach-to-the-window

The good news is that this will be ready in a few weeks, with a straightforward compatibility path for wallets and a very simple upgrade path for apps that use Wallet Adapter (#528)

**Comment by Tataklim** [comment] 2022-09-12 10:25
@jordansexton Oh that's cool!
But I still don't understand why the fallback to `window.solana` [was added](https://github.com/solana-labs/wallet-adapter/commit/5a274e0a32c55d4376d63a802f0d512947b087af)? 
`window.phantom.solana.isPhantom` has been already implemented, so they just duplicate each other, but some wallets are rewriting `window.solana` now

**Comment by jordansexton** [comment] 2022-09-12 17:28
Wallet Adapter doesn't control what wallets write to the window. It makes a best effort attempt at detection to create a better experience for end users. Because several wallets use `window.solana`, and because detecting a wallet if the user has one is better than not detecting any, the fallback exists so that a wallet is detected if it's available even if Phantom isn't there. Even if these other wallets didn't use `window.solana`, they can just use `window. phantom.solana` and then we're back at this issue, with even worse detection options. I'm closing because this isn't a bug, but the goal is for all of these workarounds to go away soon.

**Closed by jordansexton** 2022-09-12 17:28 UTC
