### ISSUE TITLE
Wallet does not disconnect, Wallet Disconnect Button stays in a perpetual "disconnecting...." state

### ISSUE THREAD

**Issue by aryan877** [solana-labs/wallet-adapter#755] opened 2023-03-21 06:42 UTC
**Describe the bug**
Disconnect Button in a never ending "disconnecting..." state when i press the Disconnect Button

**To Reproduce**
Use <WalletMultiButton /> and click on Disconnect, on the Devnet on latest version of Phantom Wallet as well as Next.js client. The issue does not exist with Solfare and other wallets, Disconnect works fine on other wallets

**Expected behavior**
I expected the wallet to disconnect

**Screenshots**
<img width="1440" alt="Screenshot 2023-03-21 at 12 09 36" src="https://user-images.githubusercontent.com/38075578/226534576-9f78512d-07f5-4005-bd50-c218dc58832d.png">

**Desktop (please complete the following information):**
MacOS 13.2.1 (Ventura)

**Additional context**
I cloned the project from a YT tutorial seems to be working fine for the Youtuber demonstrating it https://www.youtube.com/watch?v=3_zoGgffxac

**Comment by gtolarc** [comment] 2023-03-21 11:37
Me too. It seems to be an issue with @solana/wallet-standard-wallet-adapter-base, @solana/wallet-standard-wallet-adapter-react versioning from 1.01 -> 1.02, 
phantom keeps disconnecting, glow disconnects, but the following error occurs when reconnecting.

```
content.js:3 Uncaught (in promise) Error: You must connect Glow before taking other actions.
    at H (content.js:3:21460)
```

**Comment by jordansexton** [comment] 2023-03-21 17:29
Thanks for the reports, looking into this today.

**Comment by 0xsol1id** [comment] 2023-03-21 19:36
GmGn, 
I´m still using this versions

    "@solana/wallet-adapter-base": "^0.7.0",
    "@solana/wallet-adapter-phantom": "^0.7.0",
    "@solana/wallet-adapter-react": "^0.13.1",
    "@solana/wallet-adapter-react-ui": "^0.6.0",
    "@solana/wallet-adapter-solflare": "^0.4.0",
    "@solana/wallet-adapter-sollet": "^0.8.0",
    "@solana/wallet-adapter-wallets": "^0.11.3",

and havin the excact same problem, can´t disconnect from certain wallets like Phantom, but others like Slope work... still worked some days ago

**Comment by jordansexton** [comment] 2023-03-21 19:58
I've found the source of the error in Phantom. This line: https://github.com/solana-labs/wallet-standard/blob/95a482e6cf38e418217171c8eb6147bf57d85380/packages/wallet-adapter/base/src/adapter.ts#L157

When this method is called on Phantom, the awaited Promise never resolves. This means that the `finally` block which unsets the `#disconnecting` state never runs, and the adapter hangs in the disconnecting state. This bug existed before https://github.com/solana-labs/wallet-standard/pull/15. I'll need to work with the affected wallets to fix it.

**Comment by jordansexton** [comment] 2023-03-21 20:13
I can confirm that Backpack and Glow, two other wallets that implement the Wallet Standard, are not affected by this issue. Wallets that do not implement the Wallet Standard are also not affected by this specific issue.

It can be replicated in Phantom @ https://solana-labs.github.io/wallet-adapter/example/ and I have reported it to the Phantom team. I'm closing this issue for now because it's a wallet-specific bug so there's no action for us to take, but I'll comment here when it's confirmed to be fixed.

**Closed by jordansexton** 2023-03-21 20:13 UTC

**Comment by vincegnzls** [comment] 2023-03-23 00:06
Hi @jordansexton is there a temporary fix for this on our end? Like downgrading my current version in `package.json`?

**Comment by jordansexton** [comment] 2023-03-23 00:16
@vincegnzls you can check it see if pinning `@solana/wallet-standard-wallet-adapter-base` to 1.0.1 (by using npm overrides or yarn resolutions) works. I'm not sure _why_ exactly this would work, but since this was reported after 1.0.2 was published, it's worth a shot.

**Comment by jordansexton** [comment] 2023-03-23 00:18
To be clear, this will cause a _different_ issue (spurious disconnection errors on ordinary disconnections in correctly behaving wallets), but this might be a lot less serious than the most popular wallet apparently never disconnecting.

**Comment by vincegnzls** [comment] 2023-03-23 00:38
@jordansexton thanks! pinning it works, just added this in package.json:

```
"resolutions": {
  "@solana/wallet-standard-wallet-adapter-base": "1.0.1"
}
```

**Comment by jessupjn** [comment] 2023-03-23 17:31
Pinning the dependency works for me as well. The disconnect throws an error but still seems to function as I'd expect:
```
WalletConnectionError WalletDisconnectedError
     at adapter.ts:203:32
     at inpageSol.js:272:303604
     at Array.forEach (<anonymous>)
     at t.$ (inpageSol.js:272:303574)
     at t.<anonymous> (inpageSol.js:272:297300)
     at a.register.s.emit (inpageSol.js:121:38093)
     at n.<anonymous> (inpageSol.js:288:618097)
     at inpageSol.js:10:49870
     at Object.next (inpageSol.js:10:49975)
     at inpageSol.js:288:614520
```

Will keep an eye out here for when we can drop the resolution

**Comment by gtolarc** [comment] 2023-03-23 18:45
Even with version 1.01, there seems to be an error that Phantom outputs an error message and Glow does not reconnect because the context is not cleaned up when reconnecting immediately. Even if it's a problem with vendors who don't follow the wallet standard, I think it's necessary to solve the problem with major wallets.

**Comment by jordansexton** [comment] 2023-03-23 19:47
@gtolarc does any problem with Glow occur on 1.0.2? Phantom has merged a fix for the issue, but it'll take time to release to their browser extensions.

**Comment by gtolarc** [comment] 2023-03-24 08:29
@jordansexton 
This is a different issue, but the behavior is reproducible here.
https://codesandbox.io/p/sandbox/test-xovgo8
If you log in with your glow wallet, sign once, disconnect, log in with your glow wallet again, and sign, the following error occurs.
```
content.js:3 Uncaught (in promise) Error: You must connect Glow before taking other actions.
    at H (content.js:3:21460)
```
The wallet login in most web3 applications asks for a signature, so this error should occur frequently.

**Comment by chukwumaokere** [comment] 2023-03-29 06:10
I get the same error. Using the resolution solves it

> @jordansexton thanks! pinning it works, just added this in package.json:
> 
> ```
> "resolutions": {
>   "@solana/wallet-standard-wallet-adapter-base": "1.0.1"
> }
> ```

Will be watching this for a future solution

**Comment by mcintyre94** [comment] 2023-04-03 09:21
@gtolarc I think this is an issue with Glow rather than wallet-adapter, I've raised it with them. I expect it'll need an update to their extension to resolve.

**Comment by jordansexton** [comment] 2023-04-03 19:34
Thanks @mcintyre94, do you know if it affects the Glow app on iOS or Android?

**Comment by jordansexton** [comment] 2023-04-10 19:43
Phantom has fixed this in v23.4.0. This may require a manual update for now, as it's being rolled out to their userbase.

**Comment by scottwilson312** [comment] 2023-04-21 23:39
I am seeing something similar, even with the latest Phantom. When I try to do anything with the users wallet and Phantom it will throw ```he requested method and/or account has not been authorized by the user. 
{code: 4100, message: 'The requested method and/or account has not been authorized by the user```

Even though the user is logged in. Only happening on Phantom and only some of the time for some users :thinking:

**Comment by chukwumaokere** [comment] 2023-05-25 21:58
I have Phantom 23.5.0 and I;m getting this issue. 
<img width="1268" alt="image" src="https://github.com/solana-labs/wallet-adapter/assets/16673873/250518ac-222b-43ba-a192-1ce32afb39a7">
<img width="864" alt="image" src="https://github.com/solana-labs/wallet-adapter/assets/16673873/76bd6784-25ed-4f72-8036-a84c3ebc5c28">

**Comment by ronanyeah** [comment] 2023-07-11 23:44
> content.js:3 Uncaught (in promise) Error: You must connect Glow before taking other actions.

This error can currently be reproduced on the Wallet Adapter demo: https://solana-labs.github.io/wallet-adapter/example/

1. connect glow
2. sign a tx
3. disconnect glow
4. reconnect glow
5. attempt to sign tx
