### ISSUE TITLE
WalletSendTransactionError: failed to send transaction: Transaction simulation failed: Blockhash not found

### ISSUE THREAD

**Issue by hsnice16** [solana-labs/wallet-adapter#858] opened 2023-12-06 17:34 UTC
**Describe the bug**
Facing issue with [SolflareWalletAdapter.sendTransaction](https://github.com/solana-labs/wallet-adapter/blob/%40solana/wallet-adapter-wallets%400.19.23/packages/wallets/solflare/src/adapter.ts#L184)

**To Reproduce**
1. Go to https://connect-in-style.wormhole.com/
2. Connect Metamask Wallet -> Matic Network -> Matic Token 
3. Connect Solflare Wallet -> Solana Network -> Wmatic token
4. Click "Create account"
5. Check console

**Screenshots**
<img width="1389" alt="288434214-133efab6-b98d-42cb-97d4-32f74cd5288c" src="https://github.com/solana-labs/wallet-adapter/assets/56081584/f8fc4b41-a0e6-4e9a-9b19-78d1b9121975">

If you check the console, then we have `recentBlockhash` value in the print `tx`
I am using `"@solana/wallet-adapter-wallets": "^0.19.11"`

Not sure if it's a known issue.

**Comment by jordaaash** [comment] 2023-12-06 18:41
Thanks, this is not likely a bug in Wallet Adapter. Issues like this are generally issues with the app or the wallet in question. It's generally caused by using a blockhash in a transaction that the RPC the transaction is sent to hasn't observed. I'll close this issue but flag for Solflare, and they can take a look.

**Closed by jordaaash** 2023-12-06 18:41 UTC

**Comment by hsnice16** [comment] 2023-12-06 18:56
Okay. Thanks.
