### ISSUE TITLE
Sollet broken in `example` project

### ISSUE THREAD

**Issue by UncleBill** [solana-labs/wallet-adapter#239] opened 2022-01-04 10:55 UTC
**Describe the bug**

Tested with latest code da0e7c6c7e3dda23ef358d56e453961dee44353b , found out that `Sollet` was broken in the `example`.

However it works on official demo. https://solana-labs.github.io/wallet-adapter/example/

**To Reproduce**

```sh
npx lerna bootstrap
cd ./packages/starter/example
yarn dev
# then open localhost:3000
```
Choose Sollet wallet (not the extension version) from the menu, but no popup open.

**Expected behavior**

**Screenshots**

The button changes, but no popup open.

![image](https://user-images.githubusercontent.com/1141198/148048857-d15d5163-2887-429b-ad85-5fe5b7c11740.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by UncleBill** [comment] 2022-01-04 10:56
Sorry for the wrong screenshot, fixed now.

**Comment by jordansexton** [comment] 2022-01-04 17:15
Hmm, thanks the report. I'll check this out, I can't think of why it would work in the demo and not locally -- I tested it myself locally and the demo is deployed from that build.

**Comment by jordansexton** [comment] 2022-01-04 17:21
https://github.com/solana-labs/wallet-adapter#build-from-source

At a glance, it looks like the issue may be caused by how you set up the project. Running the commands here should work to build all the packages, and then you can run `yarn dev` from the example.

**Comment by jordansexton** [comment] 2022-01-05 20:31
Closing this since it works in the demo build. It looks like another issue is that you don't have `autoConnect` enabled in your screenshot.

**Closed by jordansexton** 2022-01-05 20:31 UTC
